//
// Created by arios on 27/05/2026.
//

#ifndef PROJET_DEMINEUR_RIOS_WERNER_PERAY_SAUVEGARDE_H
#define PROJET_DEMINEUR_RIOS_WERNER_PERAY_SAUVEGARDE_H
void SAUV_init();
#endif //PROJET_DEMINEUR_RIOS_WERNER_PERAY_SAUVEGARDE_H

